### PR TITLE
Removed redundant matching for management pages

### PR DESCRIPTION
**Pull request by AquaeAtrae**
Should still match both #members, /members, and /membersManage

### CODE REVIEW

**Comment by AquaeAtrae** [comment]
I'm not familiar enough with Chrome extensions to say if this constitutes version 0.6. Will it update without a version change?

**Comment by ge-ku** [comment]
Chrome store doesn't accept new uploads without incrementing version number. And looks like #members doesn't work for some reason.

**Comment by ge-ku** [comment]
Doesn't work for me, did you test it? I also tried to use "include_globs" and it just doesn't work for me with a "#" sign. I assume the reason is that it doesn't reload whole page. I'll push an update with a workaround that just replaces all links that contains "#members" with "/members" on /gropus/ pages. Feel free to make it more elegant/efficient and/or make it work like "#members" pages, without reloading whole page.

**Comment by AquaeAtrae** [comment]
Sorry, I've been busy with paid work today. But I nearly solved the issue
for the #members page which is loaded by AJAX. My folk waits for the
content on that page now, but I'm now looking for an event hook to activate
again when moving to page 2, page 3, etc. I'll send another pull request
when I've figured it all out.

Thanks again for all your support with this tool.

_Doug_  - _The long-haired red-headed guy with glasses_
-  www.darkwaters.org http://www.darkwaters.org/  *+1.720.937.DOUG ☎

**Comment by ge-ku** [comment]
Check [this (first 30 strings)](https://github.com/ge-ku/Ban-Checker-for-Steam/blob/test/checkbans.js), it detects when #members page clicked or opened. You can insert your function where "check bans when loaded" comments are.

**Comment by AquaeAtrae** [comment]
I'll look at this more closely, but I suspect it overrides Steam's BindOnHashChange() found in global.js, line 770. Not yet clear what consequences that might have. 

That's why I thought we'd have to find another event hook. Or perhaps we could override and augment the BindOnHashChange function. That would seem best.

**Pull request closed without merging**
